# Data preprocessing for model creation

## Importing the libraries

In [113]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import the dataset

In [114]:
dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(dataset)

   Travel Destination   Age  Budget  Booked Trip
0               Paris    28    1500          Yes
1           Barcelona    33     900          Yes
2              Berlin    45     NaN           No
3           Barcelona    29    1000          Yes
4               Paris    37    1800           No
5              Berlin    42    1300          Yes
6               Paris   NaN     800           No
7           Barcelona    31    1100          Yes
8              Berlin    55     NaN           No
9           Barcelona    28     950          Yes
10             Berlin    38    1100          Yes
11              Paris    26    1400           No
12          Barcelona    35    1200          Yes
13             Berlin    48    1500           No
14              Paris   NaN    1700          Yes
15          Barcelona    40    1300           No
16             Berlin    29    1000          Yes
17              Paris    44    1600           No
18          Barcelona    27     900          Yes
19             Berli

In [115]:
print(X)

[['Paris' ' 28' ' 1500']
 ['Barcelona' ' 33' ' 900']
 ['Berlin' ' 45' ' NaN']
 ['Barcelona' ' 29' ' 1000']
 ['Paris' ' 37' ' 1800']
 ['Berlin' ' 42' ' 1300']
 ['Paris' ' NaN' ' 800']
 ['Barcelona' ' 31' ' 1100']
 ['Berlin' ' 55' ' NaN']
 ['Barcelona' ' 28' ' 950']
 ['Berlin' ' 38' ' 1100']
 ['Paris' ' 26' ' 1400']
 ['Barcelona' ' 35' ' 1200']
 ['Berlin' ' 48' ' 1500']
 ['Paris' ' NaN' ' 1700']
 ['Barcelona' ' 40' ' 1300']
 ['Berlin' ' 29' ' 1000']
 ['Paris' ' 44' ' 1600']
 ['Barcelona' ' 27' ' 900']
 ['Berlin' ' 36' ' 1400']]


In [116]:
print(y)

[' Yes' ' Yes' ' No' ' Yes' ' No' ' Yes' ' No' ' Yes' ' No' ' Yes' ' Yes'
 ' No' ' Yes' ' No' ' Yes' ' No' ' Yes' ' No' ' Yes' ' No']


In [117]:
print(X)

[['Paris' ' 28' ' 1500']
 ['Barcelona' ' 33' ' 900']
 ['Berlin' ' 45' ' NaN']
 ['Barcelona' ' 29' ' 1000']
 ['Paris' ' 37' ' 1800']
 ['Berlin' ' 42' ' 1300']
 ['Paris' ' NaN' ' 800']
 ['Barcelona' ' 31' ' 1100']
 ['Berlin' ' 55' ' NaN']
 ['Barcelona' ' 28' ' 950']
 ['Berlin' ' 38' ' 1100']
 ['Paris' ' 26' ' 1400']
 ['Barcelona' ' 35' ' 1200']
 ['Berlin' ' 48' ' 1500']
 ['Paris' ' NaN' ' 1700']
 ['Barcelona' ' 40' ' 1300']
 ['Berlin' ' 29' ' 1000']
 ['Paris' ' 44' ' 1600']
 ['Barcelona' ' 27' ' 900']
 ['Berlin' ' 36' ' 1400']]


### Missing data creation
In Age and Salary there are two NaN values

In [118]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [119]:
print(X)

[['Paris' 28.0 1500.0]
 ['Barcelona' 33.0 900.0]
 ['Berlin' 45.0 1247.2222222222222]
 ['Barcelona' 29.0 1000.0]
 ['Paris' 37.0 1800.0]
 ['Berlin' 42.0 1300.0]
 ['Paris' 36.166666666666664 800.0]
 ['Barcelona' 31.0 1100.0]
 ['Berlin' 55.0 1247.2222222222222]
 ['Barcelona' 28.0 950.0]
 ['Berlin' 38.0 1100.0]
 ['Paris' 26.0 1400.0]
 ['Barcelona' 35.0 1200.0]
 ['Berlin' 48.0 1500.0]
 ['Paris' 36.166666666666664 1700.0]
 ['Barcelona' 40.0 1300.0]
 ['Berlin' 29.0 1000.0]
 ['Paris' 44.0 1600.0]
 ['Barcelona' 27.0 900.0]
 ['Berlin' 36.0 1400.0]]


## Encoding categorial data

In [120]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
cdata = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder= 'passthrough')
X = np.array(cdata.fit_transform(X))

In [121]:
print(X)

[[0.0 0.0 1.0 28.0 1500.0]
 [1.0 0.0 0.0 33.0 900.0]
 [0.0 1.0 0.0 45.0 1247.2222222222222]
 [1.0 0.0 0.0 29.0 1000.0]
 [0.0 0.0 1.0 37.0 1800.0]
 [0.0 1.0 0.0 42.0 1300.0]
 [0.0 0.0 1.0 36.166666666666664 800.0]
 [1.0 0.0 0.0 31.0 1100.0]
 [0.0 1.0 0.0 55.0 1247.2222222222222]
 [1.0 0.0 0.0 28.0 950.0]
 [0.0 1.0 0.0 38.0 1100.0]
 [0.0 0.0 1.0 26.0 1400.0]
 [1.0 0.0 0.0 35.0 1200.0]
 [0.0 1.0 0.0 48.0 1500.0]
 [0.0 0.0 1.0 36.166666666666664 1700.0]
 [1.0 0.0 0.0 40.0 1300.0]
 [0.0 1.0 0.0 29.0 1000.0]
 [0.0 0.0 1.0 44.0 1600.0]
 [1.0 0.0 0.0 27.0 900.0]
 [0.0 1.0 0.0 36.0 1400.0]]


In [122]:
print(y)

[' Yes' ' Yes' ' No' ' Yes' ' No' ' Yes' ' No' ' Yes' ' No' ' Yes' ' Yes'
 ' No' ' Yes' ' No' ' Yes' ' No' ' Yes' ' No' ' Yes' ' No']


In [123]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [124]:
print(y)

[1 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0]


## Split data into training and test data

In [125]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [126]:
print(X_train)

[[0.0 1.0 0.0 45.0 1247.2222222222222]
 [0.0 0.0 1.0 36.166666666666664 1700.0]
 [0.0 0.0 1.0 37.0 1800.0]
 [0.0 0.0 1.0 44.0 1600.0]
 [1.0 0.0 0.0 31.0 1100.0]
 [1.0 0.0 0.0 33.0 900.0]
 [0.0 1.0 0.0 48.0 1500.0]
 [0.0 0.0 1.0 28.0 1500.0]
 [0.0 1.0 0.0 36.0 1400.0]
 [1.0 0.0 0.0 27.0 900.0]
 [1.0 0.0 0.0 28.0 950.0]
 [1.0 0.0 0.0 40.0 1300.0]
 [0.0 1.0 0.0 55.0 1247.2222222222222]
 [1.0 0.0 0.0 35.0 1200.0]
 [0.0 0.0 1.0 26.0 1400.0]
 [0.0 1.0 0.0 42.0 1300.0]]


In [127]:
print(X_train[:,3:])

[[45.0 1247.2222222222222]
 [36.166666666666664 1700.0]
 [37.0 1800.0]
 [44.0 1600.0]
 [31.0 1100.0]
 [33.0 900.0]
 [48.0 1500.0]
 [28.0 1500.0]
 [36.0 1400.0]
 [27.0 900.0]
 [28.0 950.0]
 [40.0 1300.0]
 [55.0 1247.2222222222222]
 [35.0 1200.0]
 [26.0 1400.0]
 [42.0 1300.0]]


In [128]:
print(y_train)

[0 1 0 0 1 1 0 1 0 1 1 0 0 1 0 1]


In [129]:
print(X_test)

[[1.0 0.0 0.0 29.0 1000.0]
 [0.0 1.0 0.0 29.0 1000.0]
 [0.0 0.0 1.0 36.166666666666664 800.0]
 [0.0 1.0 0.0 38.0 1100.0]]


In [130]:
print(y_test)

[1 1 0 1]


## Feature scaling age, Budget

In [131]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.fit_transform(X_test[:, 3:])

In [132]:
print(X_train)

[[0.0 1.0 0.0 1.0022855253474006 -0.2602244794710717]
 [0.0 0.0 1.0 -0.09724633169606083 1.471064914560954]
 [0.0 0.0 1.0 0.006483088779737683 1.8534355782735485]
 [0.0 0.0 1.0 0.8778102207764427 1.0886942508483595]
 [1.0 0.0 0.0 -0.7403687386460095 -0.8231590677146136]
 [1.0 0.0 0.0 -0.49141812950409375 -1.5879003951398027]
 [0.0 1.0 0.0 1.375711439060274 0.7063235871357648]
 [0.0 0.0 1.0 -1.113794652358883 0.7063235871357648]
 [0.0 1.0 0.0 -0.11799221579122017 0.3239529234231702]
 [1.0 0.0 0.0 -1.238269956929841 -1.5879003951398027]
 [1.0 0.0 0.0 -1.113794652358883 -1.3967150632835055]
 [1.0 0.0 0.0 0.3799090024926113 -0.05841774028942437]
 [0.0 1.0 0.0 2.2470385710569794 -0.2602244794710717]
 [1.0 0.0 0.0 -0.24246752036217803 -0.44078840400201896]
 [0.0 0.0 1.0 -1.3627452615007987 0.3239529234231702]
 [0.0 1.0 0.0 0.628859611634527 -0.05841774028942437]]


In [133]:
print(X_test)

[[1.0 0.0 0.0 -0.9873828427975431 0.22941573387056177]
 [0.0 1.0 0.0 -0.9873828427975431 0.22941573387056177]
 [0.0 0.0 1.0 0.7634403423692347 -1.6059101370939324]
 [0.0 1.0 0.0 1.211325343225853 1.1470786693528088]]
